settings:
  # With this enabled Roleplay will use its own nickname and suffix/prefix systems.
  # If you are using an other plugin like EssentialsChat disable this.
  useNickname: true
  nicknamePrefix: '~'
  
  logging:
    # Will RoleplayChat log to console
    console: true
    
  mirrors:
    # Worlds listed here have their settings mirrored in their children.
    # The first element 'world' is the main worlds name, and is the parent world.
    # subsequent elements 'world_nether' and 'world_the_end' are worlds which will use
    # the same chat configurations as the parent.
    world:
    - world_nether
    - world_the_end    